export const blns = {
  // numbersBefore: {
  //   position: "absolute !important",
  //   width: "2px",
  //   top: "24px",
  //   backgroundColor: "#D0D4D9",
  //   content: '""',
  //   zIndex: 9,
  // },
  menuTitleStyle: {
    fontSize: "md",
  },
  menuDescStyle: {
    fontSize: "xs",
  },
  numberStyle: {
    fontSize: "sm",
    fontWeight: "semibold",
  },
  circleContainerStyle: {
    w: "24px",
    h: "24px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50px",
    border: "1px solid #1A202C",
    bgColor: "white",
    zIndex: 10,
  },
  selectedcircleContainerStyle: {
    w: "24px",
    h: "24px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50px",
    border: "1px solid #1A202C",
    bg: "#1A202C",
    color: "#fff",
    zIndex: 10,
  },
  completedCircleStyle: {
    w: "24px",
    h: "24px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50px",
    border: "1px solid #3182CE",
    bg: "#3182CE",
    color: "#fff",
    zIndex: 10,
  },
  selectedMenuTitleStyle: {
    fontSize: "md",
    fontWeight: "semibold",
  },
  selectedMenuDescStyle: {
    fontSize: "xs",
    fontWeight: "semibold",
  },
  menuContainer: {
    cursor: "default",
    position: "relative",
  },
  mainContainer: {
    w: '100%',
    flexGrow: 1,
    initial: "initial",
    animate: "collapse",
    flexDirection: "column",
    justifyContent: "space-between",
    bgColor: "gray.200",
    height: "100vh",
    px: 5,
    pb: 6,
  },
  secondRowContainer: {
    py: 5,
    borderBottom: "1px solid #D0D4D9",
    borderTop: "1px solid #D0D4D9",
  },
}
